name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./Testing/requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Start docker services
      run: | 
        cd Application
        docker compose up -d
    - name: Wait for backend to be ready
      run: docker compose wait frontend backend database database-migration --timeout 60
    - name: Run your tests
      run: pytest --tracing=retain-on-failure
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/